### ISSUE TITLE
大佬，求更新BigSur 11.0.1 20B50 正式版EFI，谢谢

### ISSUE THREAD

**Issue by wangxh86** [LiuJiangshan/Lenovo-V1000-FHD#2]
大佬，BigSur 11.0.1 20B50 正式版的驱动用不了你最新的更新的macOS Big Sur Beta 9里面的EFI。另外macOS Big Sur Beta 9这个我找了好久都没找到带oc的下载链接，黑果小兵那里好多地方都找了，求大佬分享个链接，万分感激

**Comment by LiuJiangshan** [comment]
已更新https://github.com/LiuJiangshan/Lenovo-V1000-FHD/commit/99d3b0d2ef2c85d4867a2950c457c8e97809f752
下载系统镜像建议使用https://github.com/corpnewt/gibMacOS

**Comment by wangxh86** [comment]
跪谢跪谢！么么么哒

**Comment by wangxh86** [comment]
> 已更新[99d3b0d](https://github.com/LiuJiangshan/Lenovo-V1000-FHD/commit/99d3b0d2ef2c85d4867a2950c457c8e97809f752)
> 下载系统镜像建议使用https://github.com/corpnewt/gibMacOS

不好意思，又麻烦你了，我用这种方法下载了镜像，如图
![image](https://user-images.githubusercontent.com/71023386/100432425-90794a00-30d4-11eb-809f-2a07a46e249f.png)
但是现在gibMacOS不支持Big Sur 创建安装盘了，而且也不能生成dmg安装文件，您能提供一个dmg的下载连接吗？或者告诉我怎么把我下载的文件生成的dmg吗？这样我才可以写入U盘。谢谢！

**Comment by LiuJiangshan** [comment]
https://blog.daliansky.net/macOS-BigSur-11.0.1-20B29-Release-version-with-Clover-5126-original-image-Double-EFI-Version-UEFI-and-MBR.html @wangxh86

**Comment by wangxh86** [comment]
希望没有打扰到你，我下载了https://blog.daliansky.net/macOS-BigSur-11.0.1-20B29-Release-version-with-Clover-5126-and-OC-0.6.3-and-PE-original-image.html        这个镜像，用Etcher写入U盘，在OC中导入你的EFI,然后插入U盘选择OC启动
![IMG_5670](https://user-images.githubusercontent.com/71023386/100469609-7f026300-3111-11eb-8423-9d8f007047ae.JPG)
无论我选择哪一项，都不能够正常进行
![IMG_5663](https://user-images.githubusercontent.com/71023386/100469774-e3252700-3111-11eb-8365-b93eb2b89d9a.JPG)显示这个，可是我已经在clover中删除了这两个文件（OC中没有找到这两个文件），还是会这样提示。如果可以的话，希望你能帮帮我。谢谢

**Comment by LiuJiangshan** [comment]
第一张图里选4个呢？

**Comment by wangxh86** [comment]
选第四个会出现这个，然后30秒之后自动关机了，不会重启
![IMG_5671](https://user-images.githubusercontent.com/71023386/100491110-1a202a80-315c-11eb-973a-79dd514e6425.JPG)

**Comment by LiuJiangshan** [comment]
安装的macOs系统版本？
笔记本型号？

**Comment by wangxh86** [comment]
安装的big sur正式版。笔记本是小新SR1000  CPU是i7 4500U，其他的跟v1000一样的

**Comment by wangxh86** [comment]
分辨率
1366×768

> 安装的big sur正式版。笔记本是小新SR1000 CPU是i7 4500U，其他的跟v1000一样的
分辨率
1366×768

**Comment by LiuJiangshan** [comment]
启动参数加个-no_compat_check试下
https://blog.daliansky.net/OpenCore-BootLoader.html

**Comment by wangxh86** [comment]
![截屏2020-11-29 下午8 55 19](https://user-images.githubusercontent.com/71023386/100542558-af6b0e00-3285-11eb-82f1-360e0255f663.png)
加了这个参数就搞定了。非常感谢

**Comment by wangxh86** [comment]
大佬，有个问题麻烦问一下，为啥你的显示缩放那里跟我的不一样呢？还有显示器的分辨率跟我的也不一样，是怎么设置的呢？（这几天我用这个分辨率在用某些软件的时候，菜单栏显示太小，感觉不舒服，看着你的显示很清楚，所以问一下）
![2020-12-10 11 36 26](https://user-images.githubusercontent.com/71023386/101795230-a6f6bb00-3b42-11eb-8d79-30157b3b495f.png)
![2020-12-10 11 50 04](https://user-images.githubusercontent.com/71023386/101795261-af4ef600-3b42-11eb-885b-b8f6f7a54f50.png)

**Comment by LiuJiangshan** [comment]
https://github.com/xzhih/one-key-hidpi

**Comment by wangxh86** [comment]
非常感谢，昨晚上就搞定了，今天特地来感谢
