### ISSUE TITLE
进入安装界面花屏

### ISSUE THREAD

**Issue by DamronC** [LiuJiangshan/Lenovo-V1000-FHD#3]
大佬如题，是不是内存不够的原因？目前单条4G
![IMG_20210206_150536](https://user-images.githubusercontent.com/32481016/107111688-eca6da00-688c-11eb-8d8f-b46b64870208.jpg)

**Comment by LiuJiangshan** [comment]
请贴出详细配置

**Comment by DamronC** [comment]
> 请贴出详细配置

![6a48a86a9a2b522d](https://user-images.githubusercontent.com/32481016/107121257-6b6f3780-68cc-11eb-944a-2155c571a34d.jpg)
配置上应该没问题吧

**Comment by LiuJiangshan** [comment]
配置与我的一摸一样

**Comment by LiuJiangshan** [comment]
你试下重建缓存

**Comment by DamronC** [comment]
> 你试下重建缓存



> 你试下重建缓存

我之前没有在这电脑安装过，重建缓存得进到Mac系统里边才行吧😳

**Comment by LiuJiangshan** [comment]
你安装的是哪个版本的macOs？

**Comment by DamronC** [comment]
> 你安装的是哪个版本的macOs？

大乌苏11.0.1，黑果小兵的镜像

**Comment by LiuJiangshan** [comment]
你确定使用我的引导启动的？

**Comment by DamronC** [comment]
> 你确定使用我的引导启动的？
用的就是你oc0.63的引导阿😂

**Comment by LiuJiangshan** [comment]
黑果小兵的镜像会自带一个uefi引导分区，你是怎么使用我的uefi配置的？

**Comment by DamronC** [comment]
> 你确定使用我的引导启动的？


> 黑果小兵的镜像会自带一个uefi引导分区，你是怎么使用我的uefi配置的？

我用ether写入镜像，然后用分区精灵删除原来启动盘efi分区的clover引导，再把oc引导复制过来的

**Comment by LiuJiangshan** [comment]
BIOS设置改过吗？

**Comment by DamronC** [comment]
> BIOS设置改过吗？

改过了，已经设置了uefi启动，关闭了fastboot，硬盘也设置成AHCI

**Comment by wangxh86** [comment]
> > 你确定使用我的引导启动的？
> 
> > 黑果小兵的镜像会自带一个uefi引导分区，你是怎么使用我的uefi配置的？
> 
> 我用ether写入镜像，然后用分区精灵删除原来启动盘efi分区的clover引导，再把oc引导复制过来的

你删除是clover，大佬的是oc不一样的。你要用黑锅小兵的带oc引导的系统，然后替换成大佬的oc就好了

**Comment by LiuJiangshan** [comment]
看下UEFI分区（包括ssd硬盘和u盘）下有没有 EFI > APPLE 文件夹结构？

**Comment by DamronC** [comment]
> 看下UEFI分区（包括ssd硬盘和u盘）下有没有 EFI > APPLE 文件夹结构？

没有这个文件夹
![批注 2021-02-07 074930](https://user-images.githubusercontent.com/32481016/107132352-20c7dc80-6919-11eb-9aa3-64fb67c62bc0.png)

**Comment by LiuJiangshan** [comment]
不太清楚问题在哪儿，我试过只用4gb也是正常的

**Comment by DamronC** [comment]
> 不太清楚问题在哪儿，我试过只用4gb也是正常的

![IMG_20210207_092824](https://user-images.githubusercontent.com/32481016/107133797-ebc28680-6926-11eb-9181-45564b39e348.jpg)
我重新下了个版本，原来用的是20B29的，昨天晚上下好20B50，换了个U盘重新做了启动盘，现在启动这样是不是要禁用兼容性检测？

**Comment by LiuJiangshan** [comment]
参考这个https://github.com/LiuJiangshan/Lenovo-V1000-FHD/issues/2#issuecomment-735024350

**Comment by DamronC** [comment]
> 参考这个[#2 (comment)](https://github.com/LiuJiangshan/Lenovo-V1000-FHD/issues/2#issuecomment-735024350)

加了参数之后能进安装界面，但还是花屏，会不会是我屏幕有问题😂

**Comment by LiuJiangshan** [comment]
不清楚，按理说一样的配置应该不会这样

**Comment by DamronC** [comment]
> 不清楚，按理说一样的配置应该不会这样

好吧，我再琢磨琢磨，谢谢大佬!

**Comment by wangxh86** [comment]
> > 不清楚，按理说一样的配置应该不会这样
> 
> 好吧，我再琢磨琢磨，谢谢大佬!

你先用黑果小兵的安装上，后面再配置efi就行。我有一次安装也是这样花屏，就这样解决的

**Comment by DamronC** [comment]
> > > 不清楚，按理说一样的配置应该不会这样
> > 
> > 
> > 好吧，我再琢磨琢磨，谢谢大佬!
> 
> 你先用黑果小兵的安装上，后面再配置efi就行。我有一次安装也是这样花屏，就这样解决的

用三分区引导的吗？
