### ISSUE TITLE
安装好了，触摸板鼠标指针乱点是正常现象吗？

### ISSUE THREAD

**Issue by DamronC** [LiuJiangshan/Lenovo-V1000-FHD#4]
如题

**Comment by LiuJiangshan** [comment]
你说的乱点是什么意思？

**Comment by DamronC** [comment]
就是有时候进去系统，点击一下触控板会鬼畜乱点图标，但是重启一下又正常了

**Comment by LiuJiangshan** [comment]
我的efi中触摸板驱动不是最新的，你可以换个最新的触摸板驱动试下，[VoodooPS2](https://github.com/acidanthera/VoodooPS2)。

**Comment by DamronC** [comment]
你可以看看这个视频，当时就碰了触摸板没动，链接: https://pan.baidu.com/s/18RujWoK6Jbgn1qJmSXutWA 提取码: 2nhk

**Comment by DamronC** [comment]
好的👌🏻我试试

**Comment by DamronC** [comment]
更新到最新驱动没有问题了，谢谢大佬！
