### ISSUE TITLE
从10.15.6的cl格盘换oc无法安装bigsur

### ISSUE THREAD

**Issue by DamronC** [LiuJiangshan/Lenovo-V1000-FHD#5]
如图，麻烦大佬帮忙看看。
![IMG_20210424_094704](https://user-images.githubusercontent.com/32481016/115943660-cdab0200-a4e3-11eb-8e2e-894803f9756e.jpg)

**Comment by LiuJiangshan** [comment]
改下机型吧[hardware-requirements](https://www.apple.com.cn/macos/how-to-upgrade/#hardware-requirements)

**Comment by DamronC** [comment]
解决了，谢谢大佬！
