### ISSUE TITLE
何时能解决进入win系统的问题？

### ISSUE THREAD

**Issue by richiecole** [LiuJiangshan/Lenovo-V1000-FHD#7]
谢谢你分享的EFI，我的笔记本是联想v2000，配置跟你的几乎一样，用你的EFI成功进入了big sur，但是不能进入win系统，请问大神你何时能解决进入win系统的问题呢？期待你的新EFI。

**Comment by richiecole** [comment]
我的心在等待，永远在等待哎~~~~~~~~~~~~~~

**Comment by LiuJiangshan** [comment]
可以用refind引导windows和opencore，或者直接从bios进windows
https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1887829&highlight=rEFInd

**Comment by richiecole** [comment]
谢谢你的分享，下午我试试refind。。哈哈。
