### ISSUE TITLE
hackintool 平台ID 求帮助.

### ISSUE THREAD

**Issue by richiecole** [LiuJiangshan/Lenovo-V1000-FHD#8]
大神你好。我已经用refind成功引导了win系统，但是不支持inter的网卡。怎么也装不上，后来索性换回了clover引导，成功装上了inter的无线网卡。但是我的显卡没有驱动成功。显示7m，所以我打算自己用hackintool驱动。但是问题来了，我选择了几个平台ID都不行，请问大神HD4400到底该选择什么平台ID？系统版本是big sur。
还有用hotpatch调节亮度的教程您有吗？我的QQ是 176196866 ，希望大神能帮我一下。先谢谢了！

**Comment by LiuJiangshan** [comment]
opencore下添加kext驱动还要在配置里添加，使用OpenCore Configurator.app在[Kernel-内核设置里配置](https://blog.daliansky.net/OpenCore-BootLoader.html#kernel-%E5%86%85%E6%A0%B8)
