### ISSUE TITLE
蓝牙无法使用

### ISSUE THREAD

**Issue by DamronC** [LiuJiangshan/Lenovo-V1000-FHD#9]
昨天装上用了一下，蓝牙设置能进去，但是开关没反应，然后在occ编辑了一下配置文件，把bluetoothinject.kext勾上了,重启还是用不了，并且开机很慢：(

**Comment by LiuJiangshan** [comment]
https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey
big sur 应该不需要BlueToolFixup.kext

**Comment by LiuJiangshan** [comment]
最新的只测试了macos monterey

**Comment by DamronC** [comment]
> 最新的只测试了macos monterey

好的，谢谢大佬
